#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollOneService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PayrollServiceConfig")]
	public partial class PayrollOneConfigDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCompany(Company instance);
    partial void UpdateCompany(Company instance);
    partial void DeleteCompany(Company instance);
    #endregion
		
		public PayrollOneConfigDataContext() : 
				base(global::PayrollOneService.Properties.Settings.Default.PayrollServiceConfigConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PayrollOneConfigDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PayrollOneConfigDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PayrollOneConfigDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PayrollOneConfigDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Company> Companies
		{
			get
			{
				return this.GetTable<Company>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Company")]
	public partial class Company : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CompanyId;
		
		private string _CompanyKey;
		
		private bool _IsMyPSU;
		
		private bool _Deleted;
		
		private string _ApplicationMode;
		
		private bool _SendPortalEmails;
		
		private string _ProductName;
		
		private string _DisplayName;
		
		private string _BankSortCode;
		
		private string _BankAccountNumber;
		
		private string _BankReference;
		
		private string _TraderFileSharePath;
		
		private string _PaymentFileType;
		
		private string _OmbrosDBServer;
		
		private string _OmbrosDBDatabaseName;
		
		private string _OmbrosDBUserName;
		
		private string _OmbrosDBPassword;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _Address3;
		
		private string _Address4;
		
		private string _Postcode;
		
		private string _InvoiceLogoFilename;
		
		private string _SMSSenderId;
		
		private string _EmailAddress;
		
		private string _PhoneNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCompanyIdChanging(int value);
    partial void OnCompanyIdChanged();
    partial void OnCompanyKeyChanging(string value);
    partial void OnCompanyKeyChanged();
    partial void OnIsMyPSUChanging(bool value);
    partial void OnIsMyPSUChanged();
    partial void OnDeletedChanging(bool value);
    partial void OnDeletedChanged();
    partial void OnApplicationModeChanging(string value);
    partial void OnApplicationModeChanged();
    partial void OnSendPortalEmailsChanging(bool value);
    partial void OnSendPortalEmailsChanged();
    partial void OnProductNameChanging(string value);
    partial void OnProductNameChanged();
    partial void OnDisplayNameChanging(string value);
    partial void OnDisplayNameChanged();
    partial void OnBankSortCodeChanging(string value);
    partial void OnBankSortCodeChanged();
    partial void OnBankAccountNumberChanging(string value);
    partial void OnBankAccountNumberChanged();
    partial void OnBankReferenceChanging(string value);
    partial void OnBankReferenceChanged();
    partial void OnTraderFileSharePathChanging(string value);
    partial void OnTraderFileSharePathChanged();
    partial void OnPaymentFileTypeChanging(string value);
    partial void OnPaymentFileTypeChanged();
    partial void OnOmbrosDBServerChanging(string value);
    partial void OnOmbrosDBServerChanged();
    partial void OnOmbrosDBDatabaseNameChanging(string value);
    partial void OnOmbrosDBDatabaseNameChanged();
    partial void OnOmbrosDBUserNameChanging(string value);
    partial void OnOmbrosDBUserNameChanged();
    partial void OnOmbrosDBPasswordChanging(string value);
    partial void OnOmbrosDBPasswordChanged();
    partial void OnAddress1Changing(string value);
    partial void OnAddress1Changed();
    partial void OnAddress2Changing(string value);
    partial void OnAddress2Changed();
    partial void OnAddress3Changing(string value);
    partial void OnAddress3Changed();
    partial void OnAddress4Changing(string value);
    partial void OnAddress4Changed();
    partial void OnPostcodeChanging(string value);
    partial void OnPostcodeChanged();
    partial void OnInvoiceLogoFilenameChanging(string value);
    partial void OnInvoiceLogoFilenameChanged();
    partial void OnSMSSenderIdChanging(string value);
    partial void OnSMSSenderIdChanged();
    partial void OnEmailAddressChanging(string value);
    partial void OnEmailAddressChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    #endregion
		
		public Company()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CompanyId
		{
			get
			{
				return this._CompanyId;
			}
			set
			{
				if ((this._CompanyId != value))
				{
					this.OnCompanyIdChanging(value);
					this.SendPropertyChanging();
					this._CompanyId = value;
					this.SendPropertyChanged("CompanyId");
					this.OnCompanyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyKey", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CompanyKey
		{
			get
			{
				return this._CompanyKey;
			}
			set
			{
				if ((this._CompanyKey != value))
				{
					this.OnCompanyKeyChanging(value);
					this.SendPropertyChanging();
					this._CompanyKey = value;
					this.SendPropertyChanged("CompanyKey");
					this.OnCompanyKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMyPSU", DbType="Bit NOT NULL")]
		public bool IsMyPSU
		{
			get
			{
				return this._IsMyPSU;
			}
			set
			{
				if ((this._IsMyPSU != value))
				{
					this.OnIsMyPSUChanging(value);
					this.SendPropertyChanging();
					this._IsMyPSU = value;
					this.SendPropertyChanged("IsMyPSU");
					this.OnIsMyPSUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit NOT NULL")]
		public bool Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationMode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ApplicationMode
		{
			get
			{
				return this._ApplicationMode;
			}
			set
			{
				if ((this._ApplicationMode != value))
				{
					this.OnApplicationModeChanging(value);
					this.SendPropertyChanging();
					this._ApplicationMode = value;
					this.SendPropertyChanged("ApplicationMode");
					this.OnApplicationModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendPortalEmails", DbType="Bit NOT NULL")]
		public bool SendPortalEmails
		{
			get
			{
				return this._SendPortalEmails;
			}
			set
			{
				if ((this._SendPortalEmails != value))
				{
					this.OnSendPortalEmailsChanging(value);
					this.SendPropertyChanging();
					this._SendPortalEmails = value;
					this.SendPropertyChanged("SendPortalEmails");
					this.OnSendPortalEmailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this.OnProductNameChanging(value);
					this.SendPropertyChanging();
					this._ProductName = value;
					this.SendPropertyChanged("ProductName");
					this.OnProductNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayName", DbType="NVarChar(50)")]
		public string DisplayName
		{
			get
			{
				return this._DisplayName;
			}
			set
			{
				if ((this._DisplayName != value))
				{
					this.OnDisplayNameChanging(value);
					this.SendPropertyChanging();
					this._DisplayName = value;
					this.SendPropertyChanged("DisplayName");
					this.OnDisplayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankSortCode", DbType="NChar(6)")]
		public string BankSortCode
		{
			get
			{
				return this._BankSortCode;
			}
			set
			{
				if ((this._BankSortCode != value))
				{
					this.OnBankSortCodeChanging(value);
					this.SendPropertyChanging();
					this._BankSortCode = value;
					this.SendPropertyChanged("BankSortCode");
					this.OnBankSortCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAccountNumber", DbType="NChar(10)")]
		public string BankAccountNumber
		{
			get
			{
				return this._BankAccountNumber;
			}
			set
			{
				if ((this._BankAccountNumber != value))
				{
					this.OnBankAccountNumberChanging(value);
					this.SendPropertyChanging();
					this._BankAccountNumber = value;
					this.SendPropertyChanged("BankAccountNumber");
					this.OnBankAccountNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankReference", DbType="NChar(18)")]
		public string BankReference
		{
			get
			{
				return this._BankReference;
			}
			set
			{
				if ((this._BankReference != value))
				{
					this.OnBankReferenceChanging(value);
					this.SendPropertyChanging();
					this._BankReference = value;
					this.SendPropertyChanged("BankReference");
					this.OnBankReferenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TraderFileSharePath", DbType="NVarChar(250)")]
		public string TraderFileSharePath
		{
			get
			{
				return this._TraderFileSharePath;
			}
			set
			{
				if ((this._TraderFileSharePath != value))
				{
					this.OnTraderFileSharePathChanging(value);
					this.SendPropertyChanging();
					this._TraderFileSharePath = value;
					this.SendPropertyChanged("TraderFileSharePath");
					this.OnTraderFileSharePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentFileType", DbType="NChar(30)")]
		public string PaymentFileType
		{
			get
			{
				return this._PaymentFileType;
			}
			set
			{
				if ((this._PaymentFileType != value))
				{
					this.OnPaymentFileTypeChanging(value);
					this.SendPropertyChanging();
					this._PaymentFileType = value;
					this.SendPropertyChanged("PaymentFileType");
					this.OnPaymentFileTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OmbrosDBServer", DbType="NVarChar(50)")]
		public string OmbrosDBServer
		{
			get
			{
				return this._OmbrosDBServer;
			}
			set
			{
				if ((this._OmbrosDBServer != value))
				{
					this.OnOmbrosDBServerChanging(value);
					this.SendPropertyChanging();
					this._OmbrosDBServer = value;
					this.SendPropertyChanged("OmbrosDBServer");
					this.OnOmbrosDBServerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OmbrosDBDatabaseName", DbType="NVarChar(50)")]
		public string OmbrosDBDatabaseName
		{
			get
			{
				return this._OmbrosDBDatabaseName;
			}
			set
			{
				if ((this._OmbrosDBDatabaseName != value))
				{
					this.OnOmbrosDBDatabaseNameChanging(value);
					this.SendPropertyChanging();
					this._OmbrosDBDatabaseName = value;
					this.SendPropertyChanged("OmbrosDBDatabaseName");
					this.OnOmbrosDBDatabaseNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OmbrosDBUserName", DbType="NVarChar(50)")]
		public string OmbrosDBUserName
		{
			get
			{
				return this._OmbrosDBUserName;
			}
			set
			{
				if ((this._OmbrosDBUserName != value))
				{
					this.OnOmbrosDBUserNameChanging(value);
					this.SendPropertyChanging();
					this._OmbrosDBUserName = value;
					this.SendPropertyChanged("OmbrosDBUserName");
					this.OnOmbrosDBUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OmbrosDBPassword", DbType="NVarChar(50)")]
		public string OmbrosDBPassword
		{
			get
			{
				return this._OmbrosDBPassword;
			}
			set
			{
				if ((this._OmbrosDBPassword != value))
				{
					this.OnOmbrosDBPasswordChanging(value);
					this.SendPropertyChanging();
					this._OmbrosDBPassword = value;
					this.SendPropertyChanged("OmbrosDBPassword");
					this.OnOmbrosDBPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="NVarChar(50)")]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this.OnAddress1Changing(value);
					this.SendPropertyChanging();
					this._Address1 = value;
					this.SendPropertyChanged("Address1");
					this.OnAddress1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="NVarChar(50)")]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this.OnAddress2Changing(value);
					this.SendPropertyChanging();
					this._Address2 = value;
					this.SendPropertyChanged("Address2");
					this.OnAddress2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address3", DbType="NVarChar(50)")]
		public string Address3
		{
			get
			{
				return this._Address3;
			}
			set
			{
				if ((this._Address3 != value))
				{
					this.OnAddress3Changing(value);
					this.SendPropertyChanging();
					this._Address3 = value;
					this.SendPropertyChanged("Address3");
					this.OnAddress3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address4", DbType="NVarChar(50)")]
		public string Address4
		{
			get
			{
				return this._Address4;
			}
			set
			{
				if ((this._Address4 != value))
				{
					this.OnAddress4Changing(value);
					this.SendPropertyChanging();
					this._Address4 = value;
					this.SendPropertyChanged("Address4");
					this.OnAddress4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postcode", DbType="NVarChar(10)")]
		public string Postcode
		{
			get
			{
				return this._Postcode;
			}
			set
			{
				if ((this._Postcode != value))
				{
					this.OnPostcodeChanging(value);
					this.SendPropertyChanging();
					this._Postcode = value;
					this.SendPropertyChanged("Postcode");
					this.OnPostcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceLogoFilename", DbType="NVarChar(50)")]
		public string InvoiceLogoFilename
		{
			get
			{
				return this._InvoiceLogoFilename;
			}
			set
			{
				if ((this._InvoiceLogoFilename != value))
				{
					this.OnInvoiceLogoFilenameChanging(value);
					this.SendPropertyChanging();
					this._InvoiceLogoFilename = value;
					this.SendPropertyChanged("InvoiceLogoFilename");
					this.OnInvoiceLogoFilenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMSSenderId", DbType="NVarChar(16)")]
		public string SMSSenderId
		{
			get
			{
				return this._SMSSenderId;
			}
			set
			{
				if ((this._SMSSenderId != value))
				{
					this.OnSMSSenderIdChanging(value);
					this.SendPropertyChanging();
					this._SMSSenderId = value;
					this.SendPropertyChanged("SMSSenderId");
					this.OnSMSSenderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="NVarChar(50)")]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this.OnEmailAddressChanging(value);
					this.SendPropertyChanging();
					this._EmailAddress = value;
					this.SendPropertyChanged("EmailAddress");
					this.OnEmailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(16)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
