<?xml version="1.0" encoding="utf-8"?><Database Name="PayrollOne_BetterPayments" Class="PayrollOneDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NELSON;Initial Catalog=PayrollOne_BetterPayments;Persist Security Info=True;User ID=sa" SettingsObjectName="PayrollOneService.Properties.Settings" SettingsPropertyName="PayrollOne_BetterPaymentsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.P11NI" Member="P11NIs">
    <Type Name="P11NI">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PAYEYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Frequency" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="Period" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NITableLetter" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="DirectorsNI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CorrectionOfWeek" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Supplement" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NIablePay" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ToLEL" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="LELToET" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ETToUEL" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="AboveET" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="AboveUAP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="AboveUEL" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="NIEE" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="NIER" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="NIERHol" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="RebateEE" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="RebateER" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="NIEEPreRebate" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="COMPMinEE" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="COMPMinER" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TableShouldBe" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="AdustmentApplied" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HolidayWeeks" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SCON" Type="System.String" DbType="VarChar(9)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Generation" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeCode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Payroll" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="Forenames" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="Address3" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="Address4" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="Postcode" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="Department" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="Extension" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HomePhone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JobTitle" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Dormant" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Pending" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IndustrialAction" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Joined" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LeavingDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Died" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="NINumber" Type="System.String" DbType="VarChar(9)" CanBeNull="true" />
      <Column Name="NIDirector" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NIDirectorIgnore" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NIDirectorWeeks" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NIDirectorAppt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NITable" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="InApprovedPension" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TaxCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TaxBasis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScottishTax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="P6Received" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="P6Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="P45Received" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="P45TaxablePay" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="P45Tax" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="P45StudentLoan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="P45TaxCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="P45TaxBasis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="P45DateLeftPrevious" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="P45TaxOfficeNumber" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="P45TaxOfficeReference" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="P45Period" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="P45PeriodType" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="P45Issued" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="P45NoPayUntilApril" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="P45TaxNotUsed" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="P45TaxWasWrong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EP4XStarterIssued" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EP45LeaverIssued" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="P46FilledIn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="P46TickedOption" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="P46StudentLoan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="P38SFilledIn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentLoan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaymentMethod" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SortCode" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="BankName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AccountNumber" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HoldingAC" Type="System.String" DbType="VarChar(18)" CanBeNull="true" />
      <Column Name="BankRef" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SSPMonday" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SSPTuesday" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SSPWednesday" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SSPThursday" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SSPFriday" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SSPSaturday" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SSPSunday" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BF220StartPIW" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SMPSSPStop6Mths" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SXPBabyDueDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SXPBabyBornDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SXPStillbirth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SXPNotifiedLeaveStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SMPPRIStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SXPPayAfterLeft" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SXPKitDays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SAPDateMatchNotified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SAPChildExpectedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SAPChildPlacedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AutoPaySXPType" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="NIBCertificate" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="NICDOBProof" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="NIECertificate" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="NIGCertificate" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="NIJDefermentCertificate" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="NILDefermentCertificate" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="NISDefermentCertificate" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="SCON" Type="System.String" DbType="VarChar(9)" CanBeNull="true" />
      <Column Name="LastAutoTaxYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastAutoTaxDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastAutoTaxCode" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="OmittedFromLastPaycalcs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HolidayWeeks" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HolidayEntitlement" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="HolidayBFOnRefDate" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="HolidayAccrued" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="HolidayTaken" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EMail" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NextOfKin" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MaritalStatus" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="WSEIssued" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PreviousName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CISType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TradingName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UTR" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SubVerification" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CRN" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="CISBusinessType" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="CISPartnershipUTR" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HolidayPercentage" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Tag1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tag2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tag3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tag4" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Generation" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.P11Tax" Member="P11Taxes">
    <Type Name="P11Tax">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PAYEYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Frequency" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="Period" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Supplement" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NICategory" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="NIDirector" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NICatShouldBe" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="TaxCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TaxBasis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Scottish" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TaxablePay" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Tax" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SSP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SMP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SAP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SPP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ASPP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SMPCompensation" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SAPCompensation" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SPPCompensation" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ASPPCompensation" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="StudentLoan" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="WidowsOrphans" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PreviousPay" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PreviousTax" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Complete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PayDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HolidayWeeks" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CISPrePay" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CISDeduction" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="HolidayPercentage" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="RoundingCF" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="P11EmployeeCode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ToLeaver" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RTIRandom" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="RTIHash" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="QualifyingPay" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="QualifyingPayAboveLEL" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="AEStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Generation" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Payroll" Member="Payrolls">
    <Type Name="Payroll">
      <Column Name="Payroll" Member="Payroll1" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PayrollPassword" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Frequency" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="CurrentYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CurrentPeriod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Supplement" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PeriodStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PayDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MonthlyDateMode" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="MonthlyDateModeInfo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OffsetSSP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OffsetSMP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OffsetSPP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OffsetSAP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SSPQualMon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SSPQualTue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SSPQualWed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SSPQualThu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SSPQualFri" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SSPQualSat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SSPQualSun" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeeListOrder" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BrowseDepartment" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HoursPerPeriod" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ReportsFolder" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="OrderByReports" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="GroupByReports" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ReportFont" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="SmallReportFonts" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReportStyle" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="AtYearEnd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrintZeroNetPayslips" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PermitZeroGrossCalc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PayslipStyle" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HolidayYearStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HolidayYearEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CurrentHolidayToDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DefaultHolidaysPerYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Generation" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BankTransferFormat" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CustomPayslip" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaySlipHeaderBack" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PayslipHeaderText" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PayslipTotalBack" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PayslipTotalText" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShowPensionOnPayslip" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LeaversLast" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LargeFonts" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CISEmployer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UseLineDepartment" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SuppressBankOnPayslip" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShowAddressOnSage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SuppressP32" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PayslipText" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="HolidayPayslipText" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BankList" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BeneficiaryReference" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Allow50NoteCash" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Force10NoteCash" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoundCashNetTo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PayslipMessage" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="PartPayPartPeriods" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SummarisePayslip" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PartPayMethod" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Locked" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CombineSupplementReports" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PayslipNameFormat" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PayslipEmailBody" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DefaultPaymentGroup" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Processing" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CombineSicknesses" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImportVerifyMethod" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HideLeavers" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SMSMessage" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="OccPension" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PayDayOffset" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RTIRobot" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WorkDayOffset" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastWorkDay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AEGroup" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="AEPaymentSource" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="AERollupSacrifice" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PeriodPayElement" Member="PeriodPayElements">
    <Type Name="PeriodPayElement">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Frequency" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="PAYEYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Period" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sequence" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Generated" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Variation" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="GeneratedFrom" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BackPayOffset" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Supplement" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BeforeTax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BeforeNI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BeforePension" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hours" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="Rate" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="PayValue" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Arrears" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ProtectedNet" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="EmployerValue" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Department" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="ERRate" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="AbsenceFromDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CISDeduction" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CISReference" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NetPay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NetGrossAdj" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NetValue" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Nominal" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmployerNominal" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tag1" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="Tag2" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="Tag3" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="Tag4" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="DistributionCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PensionPay" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ShortCSAReason" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Generation" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>